/**
 * Derives the orange, slate, gold and white icon sets from the crimson set.
 *
 * `crimson/*.svg` is the hand-authored source: every icon is two-tone via the classes
 * stroke-red / fill-red (main), stroke-light-red / fill-light-red (highlight) and
 * stroke-dark-red / fill-dark-red (accent). The other four sets are generated by
 * swapping in their own tones (single source of truth: ICON_SETS in
 * src/core/icon_sets.ts). Never edit the generated sets by hand.
 *
 *   bun icons/derive_sets.ts          write the four derived sets
 *   bun icons/derive_sets.ts --check  exit 1 if any derived file is out of date
 *
 * See web/icons/README.md ("Adding icons").
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { ICON_SETS } from '../src/core/icon_sets.ts';

const ROOT = import.meta.dir;
const SOURCE = 'crimson';
// The crimson source colors, as they appear in its files.
const SRC = { main: '#f43f5e', light: '#fda4af', dark: '#e11d48', monitorFill: '#0a0305', monitorStroke: '#4c1d24' };
// Dark fill/stroke of the "blackout" monitor icon, per set (not part of the tone trio).
const MONITOR: Record<string, [string, string]> = {
  orange: ['#0c0603', '#5b2a1a'],
  slate: ['#020617', '#475569'],
  gold: ['#020617', '#475569'],
  white: ['#020617', '#475569'],
};

export function derive(svg: string, setId: string): string {
  const set = ICON_SETS.find(s => s.id === setId);
  if (!set) throw new Error(`unknown set ${setId}`);
  const [main, light, dark] = set.tones;
  const [monitorFill, monitorStroke] = MONITOR[setId];
  return svg
    .replaceAll(SRC.main, main).replaceAll(SRC.light, light).replaceAll(SRC.dark, dark)
    .replaceAll(SRC.monitorFill, monitorFill).replaceAll(SRC.monitorStroke, monitorStroke)
    .replaceAll('light-red', 'light').replaceAll('dark-red', 'dark').replaceAll('-red', '-main');
}

const check = process.argv.includes('--check');
const names = readdirSync(join(ROOT, SOURCE)).filter(f => f.endsWith('.svg')).sort();
const stale: string[] = [];
for (const set of ICON_SETS) {
  if (set.id === SOURCE) continue;
  const dir = join(ROOT, set.id);
  if (!check) mkdirSync(dir, { recursive: true });
  for (const name of names) {
    const expected = derive(readFileSync(join(ROOT, SOURCE, name), 'utf8'), set.id);
    const file = join(dir, name);
    if (!existsSync(file) || readFileSync(file, 'utf8') !== expected) {
      stale.push(`${set.id}/${name}`);
      if (!check) writeFileSync(file, expected);
    }
  }
}
if (check) {
  if (stale.length) { console.error(`out of date (run: bun icons/derive_sets.ts):\n  ${stale.join('\n  ')}`); process.exit(1); }
  console.log(`derived sets are up to date (${names.length} icons x ${ICON_SETS.length - 1} sets)`);
} else {
  console.log(`wrote ${stale.length} files (${names.length} icons x ${ICON_SETS.length - 1} sets)`);
}
