use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use axum::extract::ws::{Message, WebSocket, WebSocketUpgrade};
use axum::extract::State;
use axum::response::IntoResponse;
use futures_util::{SinkExt, StreamExt};
use tokio::sync::broadcast;
use crate::core::commands::ShowCommand;
use crate::core::engine::{ShowEngine, StateSnapshot};
use crate::core::models::ToScheduleItem;

#[derive(Clone)]
pub struct AppState {
    pub engine: Arc<ShowEngine>,
    pub db: crate::storage::Database,
    pub asset_graph: Arc<crate::media::AssetGraph>,
    pub web_dir: std::path::PathBuf,
    /// Where user-downloaded/searched background media lives -- deliberately
    /// NOT under `web_dir` (see docs/paths.md): `web_dir` is read-only
    /// program content once there's a real installer, this is writable user
    /// data. Served at `/media` (see `create_router`), same URL prefix as
    /// before the split.
    pub media_dir: std::path::PathBuf,
    /// The directory `library.db` lives in -- shown as "Data Directory" in
    /// Settings (see docs/paths.md).
    pub data_dir: std::path::PathBuf,
    /// `--skip-first-time-setup` -- forces `first_run` to always report
    /// false. For automated tests, which always boot against a fresh temp
    /// database (see docs/first-time.md).
    pub skip_first_time_setup: bool,
    pub tx: broadcast::Sender<String>,
    pub plugin_manager: Arc<crate::core::plugins::PluginManager>,
    pub bible_providers: crate::storage::BibleProviderRegistry,
    pub media_search: Arc<crate::storage::MediaSearchRegistry>,
    /// The `Schedule::schedule_version` last included (non-null) in a broadcast over `tx`.
    /// Lets `broadcast_snapshot` skip re-serializing/re-sending the full schedule to every
    /// connected client when a command only touched `ShowState`. Every new connection still
    /// gets one full snapshot directly on connect (see `handle_socket`), independent of this.
    pub last_broadcast_schedule_version: Arc<AtomicU64>,
    /// `None` in `--headless`/`--no-open` mode, where there is no native window and thus
    /// nowhere to open a display output. API handlers report `available: false` in that case.
    pub display_manager: Option<Arc<crate::webview::DisplayManagerHandle>>,
    /// Active plugin authorization tokens: token -> plugin_name
    pub plugin_tokens: Arc<tokio::sync::RwLock<std::collections::HashMap<String, String>>>,
    /// Secret host session token for host console authorization
    pub host_session_token: String,
    /// Active listening server port (cleartext HTTP AV plane, default 8080)
    pub server_port: u16,
    /// Active listening HTTPS port (secure admin & pairing plane, default 8443)
    pub https_port: Option<u16>,
    /// Whether HTTPS plane is enabled and active
    pub https_enabled: bool,
    /// Ephemeral pairing sessions generated by console for mobile phone pairing bridge
    pub pairing_sessions: Arc<tokio::sync::RwLock<std::collections::HashMap<String, PairingSession>>>,
    /// Holds the `console_session_id` of whichever console is currently
    /// allowed to issue commands -- "one console at a time, first one
    /// connected wins" (see docs/CLIENT_PAIRING.md). `None` when free.
    /// Claimed the first time any host-token-authenticated request/WS
    /// message presents a `console_session_id`; released when the WS
    /// connection that claimed it disconnects (`handle_socket` below).
    pub active_console: Arc<std::sync::Mutex<Option<String>>>,
    /// One-time-delivery set for a just-authorized device's permanent
    /// pairing token. `authorize_pairing_handler` inserts a `device_id`
    /// here the instant it mints a token; `get_pairing_status_handler`
    /// (unauthenticated by design -- the TV app has no credential yet)
    /// removes it and includes the token in that single response, then
    /// never again. Without this, `/api/pairing/status?device_id=...` would
    /// hand out an already-paired device's permanent token to any LAN
    /// caller who simply names (or guesses) its `device_id`, indefinitely.
    pub pending_pairing_token_delivery: Arc<std::sync::Mutex<std::collections::HashSet<String>>>,
    /// In-memory cache of the three settings `security_headers_middleware`
    /// and the CORS origin predicate need on every single request/response
    /// (`create_router` in src/api/routes.rs) -- avoids taking `main_conn`'s
    /// mutex to re-read them from SQLite that often. Populated once at
    /// startup from whatever's persisted, and kept in sync by `post_settings`
    /// whenever one of these three keys is written.
    pub security_header_settings: Arc<std::sync::RwLock<SecurityHeaderSettings>>,
    /// Result of the last automated update check (startup, or a manual
    /// "Check for Updates" click in Settings -> About) -- see
    /// `crate::network::updater`. `GET /api/updates/status` just reads this
    /// rather than hitting GitHub on every poll. `None` until the first
    /// check (kicked off in `main.rs` shortly after startup) completes.
    pub update_status: Arc<std::sync::Mutex<Option<crate::network::updater::UpdateCheckResult>>>,
    /// Result of the last yt-dlp self-update check (startup, or every 12h
    /// after -- see `crate::network::ytdlp_updater`). `GET
    /// /api/ytdlp-updater/status` just reads this. `None` until the first
    /// check completes.
    pub ytdlp_update_status: Arc<std::sync::Mutex<Option<crate::network::ytdlp_updater::YtdlpUpdateOutcome>>>,
}

#[derive(Debug, Clone)]
pub struct SecurityHeaderSettings {
    pub csp_mode: String,
    pub frame_mode: String,
    pub cors_mode: String,
}

impl Default for SecurityHeaderSettings {
    fn default() -> Self {
        Self {
            csp_mode: "balanced".to_string(),
            frame_mode: "sameorigin".to_string(),
            cors_mode: "permissive".to_string(),
        }
    }
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PairingSession {
    pub session_token: String,
    pub created_at: i64,
    pub expires_at: i64,
}

impl AppState {
    /// Issues a unique, scoped capability token for a plugin.
    pub async fn issue_plugin_token(&self, plugin_name: &str) -> String {
        let token = format!("plg_{}", uuid::Uuid::new_v4().simple());
        let mut tokens = self.plugin_tokens.write().await;
        tokens.insert(token.clone(), plugin_name.trim().to_string());
        token
    }

    /// Resolves a plugin capability token to its associated plugin name.
    pub async fn resolve_plugin_token(&self, token: &str) -> Option<String> {
        let tokens = self.plugin_tokens.read().await;
        tokens.get(token.trim()).cloned()
    }

    /// Creates an ephemeral pairing session with TTL (in seconds, default 300)
    pub async fn create_pairing_session(&self, ttl_seconds: u64) -> String {
        let session_token = format!("pair_sess_{}", uuid::Uuid::new_v4().simple());
        let now = chrono::Utc::now().timestamp();
        let expires_at = now + ttl_seconds as i64;
        let session = PairingSession {
            session_token: session_token.clone(),
            created_at: now,
            expires_at,
        };
        let mut sessions = self.pairing_sessions.write().await;
        // Prune expired sessions
        sessions.retain(|_, s| s.expires_at >= now);
        sessions.insert(session_token.clone(), session);
        session_token
    }

    /// Validates an ephemeral pairing session token against its TTL. Does NOT
    /// consume it — a technician pairing several TVs from one console-minted
    /// session (the "Pair Another Display" flow in `pairing.html`) authorizes
    /// each device against the same still-live session, rather than the
    /// phone minting a fresh session itself (which would require the phone
    /// to hold console-level trust it was never meant to have). It naturally
    /// stops working once `expires_at` passes, same as before.
    pub async fn validate_pairing_session(&self, token: &str) -> bool {
        let now = chrono::Utc::now().timestamp();
        let sessions = self.pairing_sessions.read().await;
        sessions
            .get(token.trim())
            .map(|session| session.expires_at >= now)
            .unwrap_or(false)
    }

    /// "One console at a time, first one connected wins." `Ok(())` if
    /// `session_id` may proceed -- either it already owns the lock, or the
    /// lock was free and this call just claimed it for it. `Err(())` means a
    /// *different* console session already holds it; callers should reject
    /// the request/message with a distinct reason rather than the generic
    /// auth-failure one, so the UI can say "another console is connected"
    /// instead of implying the token itself was wrong.
    pub fn try_claim_console(&self, session_id: &str) -> Result<(), ()> {
        let mut guard = self.active_console.lock().unwrap_or_else(|e| e.into_inner());
        match guard.as_deref() {
            Some(current) if current == session_id => Ok(()),
            Some(_) => Err(()),
            None => {
                *guard = Some(session_id.to_string());
                Ok(())
            }
        }
    }

    /// Releases the console lock if `session_id` currently holds it --
    /// called when that console's WS connection disconnects. A no-op if
    /// some other session holds it (or nothing does).
    pub fn release_console_if_held(&self, session_id: &str) {
        let mut guard = self.active_console.lock().unwrap_or_else(|e| e.into_inner());
        if guard.as_deref() == Some(session_id) {
            *guard = None;
        }
    }
}

/// Shared side effects for every command entry point (HTTP `POST /api/command` and native
/// WS command messages): notify plugins, then broadcast the new state to all connected
/// clients — omitting `schedule` from the broadcast when it hasn't changed since the last
/// one, since every already-connected client already has the current schedule. Returns the
/// full, untouched snapshot so callers needing complete fidelity (an HTTP response body)
/// don't have to re-snapshot.
pub fn broadcast_snapshot(app: &AppState) -> StateSnapshot {
    let snapshot = app.engine.snapshot();
    app.plugin_manager.notify_state_change(&snapshot.state);

    let current_version = snapshot.schedule.schedule_version;
    let previous_version = app
        .last_broadcast_schedule_version
        .swap(current_version, Ordering::Relaxed);
    let schedule_changed = previous_version != current_version;

    if let Ok(mut value) = serde_json::to_value(&snapshot) {
        if !schedule_changed {
            value["schedule"] = serde_json::Value::Null;
        }
        if let Ok(json_str) = serde_json::to_string(&value) {
            let _ = app.tx.send(json_str);
        }
    }

    snapshot
}

pub async fn ws_handler(
    ws: WebSocketUpgrade,
    State(app_state): State<AppState>,
) -> impl IntoResponse {
    // Cap frame/message size (axum defaults are 16/64 MiB) and concurrent
    // sockets: /ws is readable cross-origin by design, so an unauthenticated
    // peer must not be able to pin memory or the DB mutex.
    let permit = match WS_CONNECTIONS.clone().try_acquire_owned() {
        Ok(p) => p,
        Err(_) => return (axum::http::StatusCode::SERVICE_UNAVAILABLE, "too many connections").into_response(),
    };
    ws.max_message_size(WS_MAX_MESSAGE_BYTES)
        .max_frame_size(WS_MAX_MESSAGE_BYTES)
        .on_upgrade(move |socket| async move {
            let _permit = permit;
            handle_socket(socket, app_state).await
        })
        .into_response()
}

const WS_MAX_MESSAGE_BYTES: usize = 8 * 1024 * 1024;
const WS_MAX_CONNECTIONS: usize = 256;

static WS_CONNECTIONS: std::sync::LazyLock<std::sync::Arc<tokio::sync::Semaphore>> =
    std::sync::LazyLock::new(|| std::sync::Arc::new(tokio::sync::Semaphore::new(WS_MAX_CONNECTIONS)));

/// The frame as logged / shown to plugins: credentials stripped.
fn redact_ws_envelope(value: &serde_json::Value) -> String {
    let mut v = value.clone();
    if let Some(obj) = v.as_object_mut() {
        for k in ["host_token", "device_token", "console_session_id"] {
            obj.remove(k);
        }
    }
    v.to_string()
}

async fn handle_socket(socket: WebSocket, app_state: AppState) {
    let (mut sender, mut receiver) = socket.split();

    // 1. Send initial StateSnapshot directly (as raw JSON)
    let snapshot = app_state.engine.snapshot();
    if let Ok(json_str) = serde_json::to_string(&snapshot) {
        let _ = sender.send(Message::Text(json_str)).await;
    }

    // 2. Spawn task to broadcast updates to this client. Also carries direct,
    // this-connection-only replies (e.g. a "console_locked" rejection) that
    // don't belong on the shared broadcast -- see the `direct_tx` send below.
    let mut rx = app_state.tx.subscribe();
    let (direct_tx, mut direct_rx) = tokio::sync::mpsc::unbounded_channel::<String>();
    let mut send_task = tokio::spawn(async move {
        loop {
            tokio::select! {
                msg = rx.recv() => {
                    match msg {
                        Ok(msg) => {
                            if sender.send(Message::Text(msg)).await.is_err() {
                                break;
                            }
                        }
                        Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => continue,
                        Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
                    }
                }
                Some(direct) = direct_rx.recv() => {
                    if sender.send(Message::Text(direct)).await.is_err() {
                        break;
                    }
                }
            }
        }
    });

    let app = app_state.clone();

    // 3. Process incoming messages from client
    let mut recv_task = tokio::spawn(async move {
        // Releases the "one console at a time" lock (if this connection
        // ever claimed it) when this task's future is dropped -- which
        // happens both on a clean loop exit below AND when `recv_task.abort()`
        // cancels it from the `tokio::select!` at the bottom of
        // `handle_socket` (an abrupt client disconnect, not just the loop
        // ending on its own). A plain "release after the loop" statement
        // would silently never run in the abort case, permanently wedging
        // the lock until the server restarts.
        struct ConsoleLockGuard {
            app: AppState,
            session_id: Option<String>,
        }
        impl Drop for ConsoleLockGuard {
            fn drop(&mut self) {
                if let Some(id) = self.session_id.take() {
                    self.app.release_console_if_held(&id);
                }
            }
        }
        let mut console_lock = ConsoleLockGuard { app: app.clone(), session_id: None };

        while let Some(Ok(msg)) = receiver.next().await {
            if let Message::Text(text) = msg {
                // Intercept raw JSON commands
                if let Ok(mut value) = serde_json::from_str::<serde_json::Value>(&text) {
                    let safe_text = redact_ws_envelope(&value);
                    // Paired remote-control clients (see /remote) wrap every command as
                    // {"cmd": <ShowCommand>, "device_token": "..."} so it can be checked
                    // against a real device token before executing — the raw WS text
                    // frame has no header to carry a credential in otherwise. A message
                    // with no `device_token` field is instead required to carry a
                    // `host_token` matching this server's `host_session_token` (see
                    // docs/CLIENT_PAIRING.md "Console (host) authentication") — the same
                    // in-message-envelope pattern, just for the operator console's own
                    // commands instead of a paired device's. Only the real console ever
                    // obtains that token (native injection or a loopback-only fetch), so
                    // this is what actually closes the "any LAN caller could drive the
                    // show" gap that used to exist here.
                    if let Some(token_val) = value.get("device_token") {
                        let token = token_val.as_str().unwrap_or("").trim().to_string();
                        match app.db.get_paired_device_by_token(&token) {
                            Ok(Some(dev)) => {
                                let _ = app.db.touch_paired_device(&dev.id);
                                let inner = value.get("cmd").cloned().unwrap_or(serde_json::Value::Null);
                                value = inner;
                            }
                            _ => {
                                tracing::warn!("WebSocket command rejected: invalid/unknown device token");
                                continue;
                            }
                        }
                    } else {
                        let token = value.get("host_token").and_then(|v| v.as_str()).unwrap_or("");
                        if token != app.host_session_token {
                            tracing::warn!("WebSocket command rejected: missing/invalid host token");
                            continue;
                        }
                        // "One console at a time, first one connected wins"
                        // (docs/CLIENT_PAIRING.md) -- console_session_id is a
                        // random id the frontend generates once per page
                        // load, so this connection's own reconnects/HTTP
                        // fallback keep working while a genuinely different
                        // console gets a clear, distinct rejection instead
                        // of a silent drop.
                        let session_id = value.get("console_session_id").and_then(|v| v.as_str()).unwrap_or("").trim();
                        if session_id.is_empty() {
                            tracing::warn!("WebSocket command rejected: missing console_session_id");
                            continue;
                        }
                        if app.try_claim_console(session_id).is_err() {
                            tracing::warn!("WebSocket command rejected: another console is already connected");
                            let _ = direct_tx.send(serde_json::json!({
                                "error": "console_locked",
                                "message": "Another console is already connected. Only one console can control the show at a time.",
                            }).to_string());
                            continue;
                        }
                        console_lock.session_id = Some(session_id.to_string());
                        let inner = value.get("cmd").cloned().unwrap_or(serde_json::Value::Null);
                        value = inner;
                    }

                    // Check for frontend AddToSchedule shorthand
                    if let Some(add_cmd) = value.get("AddToSchedule") {
                        if add_cmd.get("item_type").is_some() && add_cmd.get("item_id").is_some() {
                            let item_type = add_cmd["item_type"].as_str().unwrap_or("");
                            let item_id = add_cmd["item_id"].as_str().unwrap_or("");
                            
                            let sched_item = match item_type {
                                "song" => app.db.get_song_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "scripture" => app.db.get_scripture_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "media" => app.db.get_media_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "presentation" => app.db.get_presentation_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                _ => None,
                            };
                            
                            if let Some(mut item) = sched_item {
                                crate::api::routes::apply_default_theme_if_unset(&mut item, &app.db);
                                if let Ok(item_val) = serde_json::to_value(item) {
                                    let mut new_cmd = serde_json::Map::new();
                                    new_cmd.insert("AddToSchedule".to_string(), item_val);
                                    value = serde_json::Value::Object(new_cmd);
                                }
                            }
                        }
                    }

                    // Check for frontend StageItem preview shorthand — a Library
                    // Preview click staging an item that isn't in the schedule yet.
                    if let Some(stage_cmd) = value.get("StageItem") {
                        if stage_cmd.get("item_type").is_some() && stage_cmd.get("item_id").is_some() {
                            let item_type = stage_cmd["item_type"].as_str().unwrap_or("");
                            let item_id = stage_cmd["item_id"].as_str().unwrap_or("");

                            let sched_item = match item_type {
                                "song" => app.db.get_song_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "scripture" => app.db.get_scripture_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "media" => app.db.get_media_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "presentation" => app.db.get_presentation_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                _ => None,
                            };

                            if let Some(item) = sched_item {
                                if let Ok(item_val) = serde_json::to_value(item) {
                                    let mut new_cmd = serde_json::Map::new();
                                    new_cmd.insert("StageItemDirect".to_string(), item_val);
                                    value = serde_json::Value::Object(new_cmd);
                                }
                            }
                        }
                    }

                    if !app.plugin_manager.check_command(&safe_text) {
                        tracing::warn!("WebSocket command blocked by plugin: {}", safe_text);
                        continue;
                    }

                    match serde_json::from_value::<ShowCommand>(value) {
                        Err(e) => {
                            tracing::warn!("WebSocket command failed to parse, dropped: {} (raw: {})", e, safe_text);
                        }
                        Ok(cmd) => {
                            let events = app.engine.execute_command(cmd);
                            for env in &events {
                                let _ = app.db.save_event(env);
                            }
                            broadcast_snapshot(&app);
                        }
                    }
                }
            }
        }
    });

    tokio::select! {
        _ = (&mut send_task) => recv_task.abort(),
        _ = (&mut recv_task) => send_task.abort(),
    };
}
