use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::Arc;
use axum::extract::ws::{Message, WebSocket, WebSocketUpgrade};
use axum::extract::State;
use axum::response::IntoResponse;
use futures_util::{SinkExt, StreamExt};
use tokio::sync::broadcast;
use crate::core::commands::ShowCommand;
use crate::core::engine::{ShowEngine, StateSnapshot};
use crate::core::models::ToScheduleItem;

#[derive(Clone)]
pub struct AppState {
    pub engine: Arc<ShowEngine>,
    pub db: crate::storage::Database,
    pub asset_graph: Arc<crate::media::AssetGraph>,
    pub web_dir: std::path::PathBuf,
    pub tx: broadcast::Sender<String>,
    pub plugin_manager: Arc<crate::core::plugins::PluginManager>,
    pub bible_providers: crate::storage::BibleProviderRegistry,
    pub media_search: Arc<crate::storage::MediaSearchRegistry>,
    /// The `Schedule::schedule_version` last included (non-null) in a broadcast over `tx`.
    /// Lets `broadcast_snapshot` skip re-serializing/re-sending the full schedule to every
    /// connected client when a command only touched `ShowState`. Every new connection still
    /// gets one full snapshot directly on connect (see `handle_socket`), independent of this.
    pub last_broadcast_schedule_version: Arc<AtomicU64>,
    /// `None` in `--headless`/`--no-open` mode, where there is no native window and thus
    /// nowhere to open a display output. API handlers report `available: false` in that case.
    pub display_manager: Option<Arc<crate::webview::DisplayManagerHandle>>,
    /// Active plugin authorization tokens: token -> plugin_name
    pub plugin_tokens: Arc<tokio::sync::RwLock<std::collections::HashMap<String, String>>>,
    /// Secret host session token for host console authorization
    pub host_session_token: String,
    /// Active listening server port (cleartext HTTP AV plane, default 8080)
    pub server_port: u16,
    /// Active listening HTTPS port (secure admin & pairing plane, default 8443)
    pub https_port: Option<u16>,
    /// Whether HTTPS plane is enabled and active
    pub https_enabled: bool,
    /// Ephemeral pairing sessions generated by console for mobile phone pairing bridge
    pub pairing_sessions: Arc<tokio::sync::RwLock<std::collections::HashMap<String, PairingSession>>>,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct PairingSession {
    pub session_token: String,
    pub created_at: i64,
    pub expires_at: i64,
}

impl AppState {
    /// Issues a unique, scoped capability token for a plugin.
    pub async fn issue_plugin_token(&self, plugin_name: &str) -> String {
        let token = format!("plg_{}", uuid::Uuid::new_v4().simple());
        let mut tokens = self.plugin_tokens.write().await;
        tokens.insert(token.clone(), plugin_name.trim().to_string());
        token
    }

    /// Resolves a plugin capability token to its associated plugin name.
    pub async fn resolve_plugin_token(&self, token: &str) -> Option<String> {
        let tokens = self.plugin_tokens.read().await;
        tokens.get(token.trim()).cloned()
    }

    /// Creates an ephemeral pairing session with TTL (in seconds, default 300)
    pub async fn create_pairing_session(&self, ttl_seconds: u64) -> String {
        let session_token = format!("pair_sess_{}", uuid::Uuid::new_v4().simple());
        let now = chrono::Utc::now().timestamp();
        let expires_at = now + ttl_seconds as i64;
        let session = PairingSession {
            session_token: session_token.clone(),
            created_at: now,
            expires_at,
        };
        let mut sessions = self.pairing_sessions.write().await;
        // Prune expired sessions
        sessions.retain(|_, s| s.expires_at >= now);
        sessions.insert(session_token.clone(), session);
        session_token
    }

    /// Validates an ephemeral pairing session token against its TTL. Does NOT
    /// consume it — a technician pairing several TVs from one console-minted
    /// session (the "Pair Another Display" flow in `pairing.html`) authorizes
    /// each device against the same still-live session, rather than the
    /// phone minting a fresh session itself (which would require the phone
    /// to hold console-level trust it was never meant to have — see
    /// docs/GEMINI_COMMIT_REVIEW_2026-09-22.md #3). It naturally stops
    /// working once `expires_at` passes, same as before.
    pub async fn validate_pairing_session(&self, token: &str) -> bool {
        let now = chrono::Utc::now().timestamp();
        let sessions = self.pairing_sessions.read().await;
        sessions
            .get(token.trim())
            .map(|session| session.expires_at >= now)
            .unwrap_or(false)
    }
}

/// Shared side effects for every command entry point (HTTP `POST /api/command` and native
/// WS command messages): notify plugins, then broadcast the new state to all connected
/// clients — omitting `schedule` from the broadcast when it hasn't changed since the last
/// one, since every already-connected client already has the current schedule. Returns the
/// full, untouched snapshot so callers needing complete fidelity (an HTTP response body)
/// don't have to re-snapshot.
pub fn broadcast_snapshot(app: &AppState) -> StateSnapshot {
    let snapshot = app.engine.snapshot();
    app.plugin_manager.notify_state_change(&snapshot.state);

    let current_version = snapshot.schedule.schedule_version;
    let previous_version = app
        .last_broadcast_schedule_version
        .swap(current_version, Ordering::Relaxed);
    let schedule_changed = previous_version != current_version;

    if let Ok(mut value) = serde_json::to_value(&snapshot) {
        if !schedule_changed {
            value["schedule"] = serde_json::Value::Null;
        }
        if let Ok(json_str) = serde_json::to_string(&value) {
            let _ = app.tx.send(json_str);
        }
    }

    snapshot
}

pub async fn ws_handler(
    ws: WebSocketUpgrade,
    State(app_state): State<AppState>,
) -> impl IntoResponse {
    ws.on_upgrade(|socket| handle_socket(socket, app_state))
}

async fn handle_socket(socket: WebSocket, app_state: AppState) {
    let (mut sender, mut receiver) = socket.split();

    // 1. Send initial StateSnapshot directly (as raw JSON)
    let snapshot = app_state.engine.snapshot();
    if let Ok(json_str) = serde_json::to_string(&snapshot) {
        let _ = sender.send(Message::Text(json_str)).await;
    }

    // 2. Spawn task to broadcast updates to this client
    let mut rx = app_state.tx.subscribe();
    let mut send_task = tokio::spawn(async move {
        loop {
            match rx.recv().await {
                Ok(msg) => {
                    if sender.send(Message::Text(msg)).await.is_err() {
                        break;
                    }
                }
                Err(tokio::sync::broadcast::error::RecvError::Lagged(_)) => continue,
                Err(tokio::sync::broadcast::error::RecvError::Closed) => break,
            }
        }
    });

    let app = app_state.clone();

    // 3. Process incoming messages from client
    let mut recv_task = tokio::spawn(async move {
        while let Some(Ok(msg)) = receiver.next().await {
            if let Message::Text(text) = msg {
                // Intercept raw JSON commands
                if let Ok(mut value) = serde_json::from_str::<serde_json::Value>(&text) {
                    // Paired remote-control clients (see /remote) wrap every command as
                    // {"cmd": <ShowCommand>, "device_token": "..."} so it can be checked
                    // against a real device token before executing — the raw WS text
                    // frame has no header to carry a credential in otherwise. A message
                    // with no `device_token` field (the operator console's own commands)
                    // is left untouched and processed exactly as before.
                    if let Some(token_val) = value.get("device_token") {
                        let token = token_val.as_str().unwrap_or("").trim().to_string();
                        match app.db.get_paired_device_by_token(&token) {
                            Ok(Some(dev)) => {
                                let _ = app.db.touch_paired_device(&dev.id);
                                let inner = value.get("cmd").cloned().unwrap_or(serde_json::Value::Null);
                                value = inner;
                            }
                            _ => {
                                tracing::warn!("WebSocket command rejected: invalid/unknown device token");
                                continue;
                            }
                        }
                    }

                    // Check for frontend AddToSchedule shorthand
                    if let Some(add_cmd) = value.get("AddToSchedule") {
                        if add_cmd.get("item_type").is_some() && add_cmd.get("item_id").is_some() {
                            let item_type = add_cmd["item_type"].as_str().unwrap_or("");
                            let item_id = add_cmd["item_id"].as_str().unwrap_or("");
                            
                            let sched_item = match item_type {
                                "song" => app.db.get_song_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "scripture" => app.db.get_scripture_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "media" => app.db.get_media_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "presentation" => app.db.get_presentation_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                _ => None,
                            };
                            
                            if let Some(mut item) = sched_item {
                                crate::api::routes::apply_default_theme_if_unset(&mut item, &app.db);
                                if let Ok(item_val) = serde_json::to_value(item) {
                                    let mut new_cmd = serde_json::Map::new();
                                    new_cmd.insert("AddToSchedule".to_string(), item_val);
                                    value = serde_json::Value::Object(new_cmd);
                                }
                            }
                        }
                    }

                    // Check for frontend StageItem preview shorthand — a Library
                    // Preview click staging an item that isn't in the schedule yet.
                    if let Some(stage_cmd) = value.get("StageItem") {
                        if stage_cmd.get("item_type").is_some() && stage_cmd.get("item_id").is_some() {
                            let item_type = stage_cmd["item_type"].as_str().unwrap_or("");
                            let item_id = stage_cmd["item_id"].as_str().unwrap_or("");

                            let sched_item = match item_type {
                                "song" => app.db.get_song_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "scripture" => app.db.get_scripture_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "media" => app.db.get_media_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                "presentation" => app.db.get_presentation_by_id(item_id).ok().flatten().map(|i| i.to_schedule_item()),
                                _ => None,
                            };

                            if let Some(item) = sched_item {
                                if let Ok(item_val) = serde_json::to_value(item) {
                                    let mut new_cmd = serde_json::Map::new();
                                    new_cmd.insert("StageItemDirect".to_string(), item_val);
                                    value = serde_json::Value::Object(new_cmd);
                                }
                            }
                        }
                    }

                    if !app.plugin_manager.check_command(&text) {
                        tracing::warn!("WebSocket command blocked by plugin: {}", text);
                        continue;
                    }

                    if let Ok(cmd) = serde_json::from_value::<ShowCommand>(value) {
                        let events = app.engine.execute_command(cmd);
                        for env in &events {
                            let _ = app.db.save_event(env);
                        }
                        broadcast_snapshot(&app);
                    }
                }
            }
        }
    });

    tokio::select! {
        _ = (&mut send_task) => recv_task.abort(),
        _ = (&mut recv_task) => send_task.abort(),
    };
}
